modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "GNU GPLv3" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/DragonMounts-Team/NeoDragonMounts/issues"
[[mods]] #mandatory
modId = "neodragonmounts" #mandatory
version = "0.1.0" #mandatory
displayName = "Dragon Mounts 2" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL="https://github.com/DragonMounts-Team/NeoDragonMounts"
logoFile="neodragonmounts.png" #optional
credits="" #optional
authors = "" #optional
description = '''As a sequel to Dragon Mounts, this mod adds over 15 new dragons to your game. In addition to new dragons, the mod adds in new armors and tools for players, Armors for Dragons, Nests that generates in every world, New Dragon breeds, and much more.''' #mandatory (Supports multiline text)
[[mixins]]
config = "neodragonmounts.mixins.json"
[[dependencies.neodragonmounts]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.4.136,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.neodragonmounts]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.21.4, 1.21.5)"
ordering = "NONE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.neodragonmounts]
#openGLVersion="[3.2,)"
